### ISSUE TITLE
Warning:  preg_match(): Compilation failed: invalid range in character class at offset 4

### ISSUE THREAD

**Issue by stasovskyj** [matgargano/simplehtmldom#2]
Please update your class. Line 1365
`if (!preg_match("/^[\w-:]+$/", $tag)) // this will not work in PHP >= 7.3`
use  :
`if (!preg_match("/^[\w\-:]+$/", $tag)) `
And change the line 684 to
` $pattern = "/([\w\-:\*]*)(?:\#([\w\-]+)|\.([\w\-]+))?(?:\[@?(!?[\w\-:]+)(?:([!*^$]?=)[\"']?(.*?)[\"']?)?\])?([\/, ]+)/is";`

**Comment by matgargano** [comment]
Issue a PR
